### PR TITLE
Reduce duplicate queries on instrument list view

### LINKED ISSUE #141: Reduce queries on Instrument List view
The InstrumentList view contains tons of duplicate queries...
image

Not the biggest deal at the moment, but an easy optimization that will pay dividends!

### PR DESCRIPTION
**Pull request by dchiller**
This PR refactors the `InstrumentList` view and associated templates to reduce the number of database queries. See profile:
image

We now select and prefetch related objects, using a custom related objects manager to filter instrument names on the backend, rather than during template rendering (the cause of a great many of the duplicate queries).

The PR also adds some additional python development dependencies to the `pyproject.toml` file:
- `djlint` was configured for html template formatting but had not been added as a dependency
- stubs for the `django` and `requests` packages are added for type checking

Closes #141

### CODE REVIEW

**Comment by kunfang98927** [comment]
It looks good! @dchiller  I only have a few questions:

- When I run `docker compose build`, it has the following error message:
image

But when I change the poetry version to the latest version (`pip install poetry==1.8.3`) in the 4th line of `install-packages.sh`, `docker compose build` can then be run successfully.

Do you think we need to upgrade poetry? Is the error message related to the poetry version?


- This question is not related to this PR. In Django DevTool, the `static files` tab always has `500: internal server error`. Do you know what the reason is?
image

**Comment by dchiller** [comment]
> Do you think we need to upgrade poetry? Is the error message related to the poetry version?

Whoops! You're right, `package-mode = false` support was [added in poetry 1.8](https://github.com/python-poetry/poetry/releases/tag/1.8.0), which is what I have locally, but not what the container build uses. I'll add this to the PR. Thanks!

**Comment by dchiller** [comment]
> * This question is not related to this PR. In Django DevTool, the `static files` tab always has `500: internal server error`. Do you know what the reason is?

I'm seeing the following error in the `app` container logs:

 `django.core.exceptions.SuspiciousFileOperation: The joined path (/js/GoogleTranslate.js) is located outside of the base path component (/virtual-instrument-museum/vim-app/VIM/static)`

I'll take a closer look tomorrow.

**Review by kunfang98927 — APPROVED** [review]

**Comment by dchiller** [comment]
@kunfang98927 The issue with the static files turns out to be here:

https://github.com/DDMAL/VIM/blob/30e5a4f94745de601484c00cd56e08ab61006374/web-app/django/VIM/templates/base.html#L105-L108

The parameter to the `static` tag should be a relative and not an absolute path (ie. if we get rid of the opening slash on "/js/GoogleTranslate.js" and "/js/LanguageTooltip.js", it's fine).

**Pull request merged**
